spring:
  application:
    name: eureka-client

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    preferIpAddress: false
    instanceId: ${eureka.instance.hostname}:${spring.application.name}:${random.int}
    securePortEnabled: false
    nonSecurePortEnabled: true
    leaseRenewalIntervalInSeconds: 30
